### ISSUE TITLE
Create interceptors

### ISSUE THREAD

**Issue by AlexShukel** [ArtiomTr/stocked#57]
In my project, before stock values set and observers are called, I must ask an user to decide if he wants it or not. So, one option should be to write my own function which on some conditions should call `setValue` or not. But there is another problem, that many components have access to value path which not always must to change, and can `useStockState` on their own to change that value. So I see a good feature to provide `interceptors` in `useStock` hook with `initialValues`. Object type should be:
```ts
type Interceptors = undefined | Record<T, () => Promise<boolean>>
```
This interceptor function should be called before setting value in stock.

**Comment by ArtiomTr** [comment]
Interceptors inside useStock hook isn't good solution, because it leads to not clear behavior. Setting value must be straightforward as possible.
